version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: app
    ports:
      - 8080:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env-non-dev